{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "greenthumb.fullname" . }}
  labels:
    {{- include "greenthumb.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "greenthumb.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
  egress:
    # Allow DNS resolution
    - to: []
      ports:
      - protocol: UDP
        port: 53
    # Allow HTTPS outbound (for external APIs if needed)
    - to: []
      ports:
      - protocol: TCP
        port: 443
{{- end }}